### ISSUE TITLE
implement SAVE and LOAD

### ISSUE THREAD

**Issue by nippur72** [leomil72/LM80C#12]
currently the only way of loading programs is via terminal emulation over serial, this means you can't load or save true binary files, or even BASIC programs in its native tokenized form.

My proposal is to have the commands `SAVE` and `LOAD` to transfer programs over the existing serial line. The protocol could be like as this:
- sync byte (repeated n times)
- 4 bytes header 
- 1 byte type of file (binary at fixed address or basic relocatable)
- filename + 0x00
- (word) number of bytes
- (word) address 
- actual bytes
- (word) checksum

(note: the `LOAD` command have to set the `PROGND` pointer at the end of the loading). 

If slower baudrates are allowed (e.g. 2400), it would be possible to SAVE and LOAD from a cassette tape (or any other audio source) like a real home computer of the '80s 😄. (In such case the header bytes at the start are mandatory to throw away the random characters).

**Comment by leomil72** [comment]
The PCB I realized is a little bit different from the online schematics and it has an Atmega328 on the second serial line of the SIO that should act as a driver to read from/write to a micro SD. I chose this way since this isn't really a break of my proposal to not use components out of the Z80 family. In fact in the past many drives or other peripherals had their own CPU/OS on the device that got commands from the CPU and talked with the device

**Comment by leomil72** [comment]
PS: I surely wanted to replicate an 8 bit system of the 80s but I also wanted to build something that could be usable with contemporary technology. Today analog music tapes are out of the market for a long time now, SD cards are widely available so I opted for them. Moreover I fly!d use the PIO to access the SD card but I realized that it would have been a very hard task, so I decided for another approach

**Comment by nippur72** [comment]
curious to see what is the other approach. I have limited experience with SD cards so can't help much, sorry. 

P.S. in case you need to to actually transfer binary files, the emulator has a function named `make_lm()` that automatically creates a BASIC program with DATA for you :-) 

From the JavaScript console (F12):
```
> make_lm(0xA000,0xA00F)

10 FOR T=&Ha000 TO &Ha00f
20 READ B:POKE T,B
30 NEXT
40 SYS &Ha000
50 END
1000 DATA 0,0,0,0,0,0,0,0
1010 DATA 0,0,0,0,0,0,0,0
```
