### ISSUE TITLE
implement printing in screen 2

### ISSUE THREAD

**Issue by nippur72** [leomil72/LM80C#13]
BASIC should be able to print in `screen 2` mode, allowing to change foreground and background colors on per-character basis. This way programs could me more "colorful" without the limitations imposed by `screen 1`.

Best would be have the BASIC prompt in `screen 2` and allow full editing, in other words treating `screen 2` like a text mode (perhaps this could be the only text mode supported by the firmware--the others are not very useful).

Advantages:
- more colors! 
- reverse characters possible (by inverting colors)
- cursor blinking with reverse or other effect (e.g. a colorful cursor)

Disvantages:
- needs to keep a separate buffer for screen map and color map 40 x 24 x 2 (could these buffers be placed in VRAM ?)
- slow to scroll and to print to

The Amstrad CPC does it this way: it has the prompt and the editing in graphic mode and has a non-blinking reversed cursor.

**Comment by nippur72** [comment]
I wrote the assembly subroutine for printing a single character in `screen 2` mode. But I don't know how to connect it to the rest of the firmware.

If you want to merge it it's [here](https://github.com/nippur72/lm80c-emu/blob/master/software/screen2_putc/screen2_putc.asm), it's 62 bytes long.

Hello world:
![image](https://user-images.githubusercontent.com/2598443/80918473-773e3400-8d65-11ea-892d-bd2e73a83e2b.png)

Screen filled
![image](https://user-images.githubusercontent.com/2598443/80918610-2aa72880-8d66-11ea-8bf1-c4d71b4668bb.png)

![image](https://user-images.githubusercontent.com/2598443/80918652-59250380-8d66-11ea-8359-e6ebf76c68fb.png)

**Comment by leomil72** [comment]
Good improvement but... a text mode is a text mode and the LM80C was built over the TMS9918 with its limits and its disadvantages. In fact, each home computer of the 80s had its own hardware and acted in a different way. So did the ZX Spectrum, so did my C16 and so did the C64 and the MSX.
My C16 had a command to write characters on a graphic mode but it was just to add some text to a graphic, not just to use the graphics mode as a text screen. Consider that in screen 0, 1, or 4 you just use a single tile to print a char while in screen 2  your system should plot 64 pixels for each char. Not considering the buffers: 960 bytes for the chars and 960 bytes for the colors: I really don't know without looking at the data sheet if I could find 2 kb of empty space in Vram when in G2 but I don't think so.

BTW I can implement a sort of CHAR command to print in G2 , this could be useful for splash screens, static images or program-driven screens, but it could never become the default text mode , actually

**Comment by nippur72** [comment]
yes a `CHAR` or `GPRINT` or something similar would be enough to let BASIC programs make use of screen 2. Or perhaps one could just use `SYS` to call a machine language routine as I did. On the Commodores the `SYS` command allowed to pass extra parameters -- not thanks to `SYS` itself, but calling the BASIC parser at the start of ML routine. I wonder if the same trick works on the LM80C as well.

**Comment by leomil72** [comment]
I prefer a specific BASIC command instead of calling a ML routine since if the user is using the BASIC interpreter then this means that he/she isn't so skilled to work with LM.
Actually, SYS can get an argument and pass it to the called ML routine into the accumulator (reg. A).

**Comment by leomil72** [comment]
It'll be implemented in next R3.10

**Comment by nippur72** [comment]
talking of screen modes, can we have `SCREEN 4` as the default/boot mode instead of 1? My understanding is that there are no differences except that in `SCREEN 4` you can set the colors on a tile basis instead of group of tiles.

**Comment by leomil72** [comment]
I added G4 after a lot of development in which G1 was the boot mode so at the moment this still continue to be the default mode. 

PS: G4 has some little differences with G1. It has less sprites (8 instead of 32),it supports color on tile basis but if you change the color of a tile this change will be reflected to all the same tiles on the screen, because it isn't a real multicolor mode.
