### ISSUE TITLE
TMRCNT timer accuracy

### ISSUE THREAD

**Issue by nippur72** [leomil72/LM80C#17]
I spent the whole morning debugging why `0 PRINT TMR(0)/100:GOTO 0` was not counting seconds as it was supposed to do. I checked almost everything in the emulator -- only many hours later I realized that the act of calling `TMR(0)` does affects the counting itself! That's because of the `DI` and `EI` instructions used in the `TMR` routine. So if you call it repeatedly, counting slows down considerably. Scrolling the video also slows it to a certain extent, I guess for the same reason (VDP accesses are in `DI` mode). 

I don't think much can be done to fix this issue, perhaps the only thing would be reducing the 100Hz frequency of the CH3 timer, in order to mitigate the chance of missed increments. With prescaler set to `256` the next good value would be 60 Hz (constant value 240).

**Comment by leomil72** [comment]
I introduced EI/DI instructions to atomize the reading of the timer registers, avoiding a race condition (both the interrupt and the user are accessing the same memory cells).
It is not intended to be read repeatedely or for long periods. 100 hz have been chosen to simplify counting, I dislike 50/60 Hz interrupts from old PAL/NTSC video chip interrupts.
Maybe there could be a way to get around the problem: I could change the code and change the double reading of two single bytes from RAM into a single reading of a word from RAM (i.e. LD HL,(nnnn)). In fact, the interrupt is acknowledged and managed at the end of any instruction

**Comment by nippur72** [comment]
I agree 60 is an ugly number (unless you are an ancient babilonian 🤣).

When the cursor is idle (no input etc), I counted an average of 2320 T-states starting from the CTC interrupt request to the `RETI` instruction. That means the interrupt routine takes 6.29 % of the total CPU time (2320 x 100 / 3686400). At 60 Hz it would be 3.77% -- a little advantage of lowering the frequency.

BTW, looking at the CTC, I was surprised to discover it can only count up to 256. Or is there a way to make it count for longer periods?

**Comment by leomil72** [comment]
> That means the interrupt routine takes 6.29 % of the total CPU time (2320 x 100 / 3686400). At 60 Hz it would be 3.77% -- a little advantage of lowering the frequency.

The heavier portion of code is the keyboard management, I think. I could reduce this % by simply doing a keyboard reading every 2 interrupt calls, getting a 50 Hz frequency without altering the time counting.

> BTW, looking at the CTC, I was surprised to discover it can only count up to 256. Or is there a way to make it count for longer periods?

Because it only has 8-bit registers, the only way to change get around this issue is to play with prescalers and time constants (the values reloaded automatically when registers reach 0).

**Comment by leomil72** [comment]
Or maybe you could try to daisy-chain the interrupt output pin of a timer with the input pin of a counter. So when the first one reaches zero it raises an interrupt, mirrored on the external pin: this signal will be counted by the counter and, when reached the desired value, this one in turn will raise an interrupt for the CPU. I don't see any other ways without using additional external components.

**Comment by leomil72** [comment]
> >  That means the interrupt routine takes 6.29 % of the total CPU time (2320 x 100 / 3686400). At 60 Hz it would be 3.77% -- a little advantage of lowering the frequency.

> The heavier portion of code is the keyboard management, I think. I could reduce this % by simply doing a keyboard reading every 2 interrupt calls, getting a 50 Hz frequency without altering the time counting.

Ok, I did it. A simple check on bit#0 of the lowest byte of the 32-bit system timer at each interrupt call: the keyboard reading is done only if such bit is 0, meaning every 2 interrupt calls (50 Hz).
