### ISSUE TITLE
how to read/write from serial in BASIC

### ISSUE THREAD

**Issue by nippur72** [leomil72/LM80C#3]
once you open the `SERIAL` line communication, how do you send/receive data in BASIC ?

**Comment by leomil72** [comment]
Despite the SIO supports 2 serial ports, at the moment only port A is supported by the kernel and configured to work as a stream device. In fact, it's been thinked to work with a terminal emulator running on a remote computer, and, when opened, it just sends chars being printed on video to the remote device and prints on video chars that are input on the terminal emulator. In a future release kernel will support port B, too, to act as a block device to exchange data with a mass storage device
