### ISSUE TITLE
bug: keyboard sequence that boots the LM80C

### ISSUE THREAD

**Issue by nippur72** [leomil72/LM80C#6]
at the command prompt, if I type `CTRL`+`H` and then `RETURN` the machine does reset.

Firmware 3.7.

**Comment by leomil72** [comment]
Strange.... I don't know why... o__O
I'll investigate...

**Comment by leomil72** [comment]
Uhm, maybe I understand what's happening. This is not a bug, it's related to the way the BASIC interpreter stores the statements, using a pseudo-tokenized form that is composed by the ASCII code of the first letter of the command to whom $80 is added, and the rest of letters as they appear. So, for some reason it parses the CTRL+H graphic char as the tokenized form of RESET. In fact, if you play with CTRL and press some random combinations you'll got several BASIC messages like "Missing operand", "Illegal function call", etc.... I'll have to fix the parser and cut out everything with an ASCII code >=128.

**Comment by leomil72** [comment]
Solved.
