### ISSUE TITLE
arrangement of function keys in 3.7 

### ISSUE THREAD

**Issue by nippur72** [leomil72/LM80C#7]
keys from 4 to 8 do not match the actual key labels of a C16 keyboard, e.g key #4 is not `F4` (`SHIFT`+`F1`) but it's 'F5' (`SHIFT`+`F2`). `HELP` is not key #8 but #4. Is that intentional?

I've re-checked it and I think I got it right in the emulator.

**Comment by leomil72** [comment]
You're late ;-)
I myselft discovered this bug this morning and already fixed in the code
BTW, thanks for reporting
